"""Agent system prompts."""

from agentic.agent.prompts.system import ANSWER_STYLE

from agentic.agent.prompts.evidence_fs import (
    BASE_SYSTEM_PROMPT,
    EVIDENCE_FS_SYSTEM_PROMPT,
    EVIDENCE_FS_SEMANTIC_SUFFIX,
    EVIDENCE_FS_MULTIMODAL_SUFFIX,
)

from agentic.agent.prompts.rag_business import RAG_BUSINESS_SYSTEM_PROMPT

from agentic.agent.prompts.web_system import WEB_RAG_SYSTEM_PROMPT

from agentic.agent.prompts.insurance import (
    CLAIM_CHECK_SYSTEM_PROMPT,
    COMPARE_SYSTEM_PROMPT,
    FRAUD_PPR_SYSTEM_PROMPT,
    POLICY_CALC_SYSTEM_PROMPT,
    RECOMMEND_SYSTEM_PROMPT,
    RISK_PREDICT_SYSTEM_PROMPT,
)

__all__ = [
    "ANSWER_STYLE",
    "BASE_SYSTEM_PROMPT",
    "EVIDENCE_FS_SYSTEM_PROMPT",
    "EVIDENCE_FS_SEMANTIC_SUFFIX",
    "RAG_BUSINESS_SYSTEM_PROMPT",
    "WEB_RAG_SYSTEM_PROMPT",
    "CLAIM_CHECK_SYSTEM_PROMPT",
    "COMPARE_SYSTEM_PROMPT",
    "FRAUD_PPR_SYSTEM_PROMPT",
    "POLICY_CALC_SYSTEM_PROMPT",
    "RECOMMEND_SYSTEM_PROMPT",
    "RISK_PREDICT_SYSTEM_PROMPT",
]
