/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["list_all_files_get"];
        put?: never;
        /** Upload */
        post: operations["upload_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get One */
        get: operations["get_one_files__file_id__get"];
        put?: never;
        post?: never;
        /** Delete One */
        delete: operations["delete_one_files__file_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_files__file_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_id}/jobs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Jobs
         * @description Subscribe to the latest ingest job's stage progress.
         *
         *     Three terminal cases:
         *
         *     1. Latest job is ``running`` and a bus is registered — stream live
         *        ``stage`` / ``final`` / ``done`` frames from the bg task.
         *     2. Latest job is ``running`` but the bus has not registered yet
         *        (race against ``BackgroundTasks`` scheduling) — short poll up
         *        to 2 s, then stream live frames.
         *     3. Latest job is already terminal (``done`` / ``failed``) — synthesize
         *        a single ``final`` + ``done`` from the row so the client always
         *        sees a closed stream.
         *
         *     The "wait timed out AND row is still nonterminal" path refetches the
         *     row before falling back to terminal replay so we don't synthesize a
         *     spurious ``failed`` for a job whose bg task is just slow to schedule.
         *
         *     Multi-subscriber: the bus is constructed with
         *     ``replay_buffered=True`` so each ``stream()`` call gets its own
         *     queue, seeded with the full event history. The FilesPage
         *     minimized-ingest chip and any extra browser tabs all see the
         *     same timeline.
         */
        get: operations["stream_jobs_files__file_id__jobs_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Original
         * @description Stream back the cached upload (so the frontend's react-pdf can render
         *     it for the citation drawer).
         */
        get: operations["download_original_files__file_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Page Preview
         * @description Render-on-demand JPG of any 1-based ``page`` of the cached PDF.
         *
         *     Default ``page=1`` powers the FilesPage card thumbnail; the
         *     full-file preview drawer scrolls through ``?page=N`` for each
         *     visible page. Output is cached under
         *     ``local_storage/preview/<file_id>/p_NNNN.jpg`` and re-served on
         *     subsequent hits. Re-ingest invalidates the cache (see
         *     ``purge_file_artifacts``).
         *
         *     The previous implementation served PaddleOCR's layout-detection
         *     visualization (``layout_det_res_0.jpg``) which had bounding boxes
         *     overlaid — visually it looked like a CV debug screenshot rather
         *     than a page thumbnail. We now render via pypdfium2 (PDFium, the
         *     same engine Chromium uses).
         */
        get: operations["page_preview_files__file_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_id}/page-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Page Count Endpoint
         * @description Cheap page-count probe for the full-file preview drawer.
         *
         *     Reads the PDF's xref via pypdfium2 — no rendering, returns within a
         *     few ms even for hundred-page documents. Falls back to the
         *     ``files.page_count`` row column when the PDF is unreadable so the
         *     UI still gets a usable bound.
         */
        get: operations["page_count_endpoint_files__file_id__page_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_id}/reingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reingest */
        post: operations["reingest_files__file_id__reingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["list_audit_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit Entry */
        get: operations["get_audit_entry_audit__entry_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_chat_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_chat_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session Detail
         * @description Session header + full message list. Light enough for chat history view.
         */
        get: operations["get_session_detail_chat_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_chat_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /** Patch Session */
        patch: operations["patch_session_chat_sessions__session_id__patch"];
        trace?: never;
    };
    "/chat/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Session Message
         * @description Stream the assistant reply for a new user message in this session.
         *
         *     Lifecycle:
         *
         *     1. Validate session + ownership.
         *     2. Persist user message + **explicitly commit + bump session.updated_at**
         *        so concurrent ``GET`` sees the new turn even while the stream is
         *        mid-flight. We don't rely on the ``get_session`` dep tail-commit
         *        because FastAPI dependency teardown happens after the response
         *        body finishes iterating, and a client disconnect mid-stream
         *        would otherwise roll back the user message.
         *     3. Open the SSE response. The runner runs the pipeline / agent,
         *        streams events, and resolves a result-future once it returns.
         *     4. After the bus drains we ``await`` the future (shielded against
         *        response-task cancellation) and write the assistant message
         *        inside a fresh DB session.
         */
        post: operations["post_session_message_chat_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rag Stream
         * @description Smoke endpoint: streams a RAG answer with no session persistence.
         */
        post: operations["rag_stream_rag_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Agent Stream
         * @description Smoke endpoint: streams a base/proof/graph/web agent run, no persistence.
         *
         *     ``body.web=True`` swaps in the dedicated web agent singleton with
         *     its own kwargs map. Schema validation already rejected the
         *     forbidden combos (web=True + proof/graph).
         */
        post: operations["agent_stream_agent_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/web-rag/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Web Rag Stream
         * @description Smoke endpoint: streams a single-call web RAG, no persistence.
         */
        post: operations["web_rag_stream_web_rag_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_admin_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Config */
        patch: operations["patch_config_admin_config_patch"];
        trace?: never;
    };
    "/admin/config/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schema */
        get: operations["get_schema_admin_config_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/config/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Reset Config */
        delete: operations["reset_config_admin_config__key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/refresh-indexes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Indexes
         * @description Force-reload PageStore / InventoryStore / GraphPPRChannel from disk.
         *
         *     Normally ingest tasks call the same hook themselves on every
         *     successful parse / reingest / delete, so an admin will only reach
         *     for this when something wrote to ``local_storage`` out of band
         *     (manual scripts, restored backups). Returns 204 — caller may verify
         *     via the next /graph/sample or /files request.
         *
         *     503 when the singletons aren't wired (lifespan didn't run; rare
         *     outside test clients without lifespan).
         */
        post: operations["refresh_indexes_admin_refresh_indexes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_admin_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_admin_users__user_id__get"];
        put?: never;
        post?: never;
        /** Soft Delete User */
        delete: operations["soft_delete_user_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Patch User */
        patch: operations["patch_user_admin_users__user_id__patch"];
        trace?: never;
    };
    "/admin/users/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_admin_users__user_id__reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview_graph_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Seed */
        get: operations["search_seed_graph_seed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sample Graph
         * @description Random vertex sample (entity-first) — first-paint canvas filler.
         *
         *     Cached per-n for the process lifetime so mode switches in the
         *     GraphPage don't reshuffle the underlying canvas under the user.
         */
        get: operations["sample_graph_graph_sample_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph/expand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Expand Node */
        get: operations["expand_node_graph_expand_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph/nodes/{hash_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Node Detail
         * @description Hover-card payload. Response body deliberately omits ``hash_id`` —
         *     the URL already carries it and the frontend renders pure prose.
         */
        get: operations["get_node_detail_graph_nodes__hash_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph/ppr-subgraph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ppr Subgraph
         * @description Re-run the PPR channel for ``body.query`` and return the visualizable
         *     subgraph (seeds + actived entities + passages + induced edges).
         *
         *     ~300-500ms on a warm channel; the RAG-PPR drawer in the chat UI
         *     calls this when the user clicks "show subgraph" on a graph_ppr hit.
         */
        post: operations["ppr_subgraph_graph_ppr_subgraph_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insurance/compare/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare Stream */
        post: operations["compare_stream_insurance_compare_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insurance/exclusion-audit/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exclusion Audit Stream */
        post: operations["exclusion_audit_stream_insurance_exclusion_audit_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insurance/recommend/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommend Stream */
        post: operations["recommend_stream_insurance_recommend_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insurance/claim-check/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim Check Stream */
        post: operations["claim_check_stream_insurance_claim_check_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insurance/policy-calc/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Policy Calc Stream */
        post: operations["policy_calc_stream_insurance_policy_calc_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insurance/fraud-ppr/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fraud Ppr Stream
         * @description Single PPR retrieval + streamed LLM analysis.
         *
         *     Used by the Policy Review workbench's "hidden risk" tab. The
         *     runner pre-fetches the PPR subgraph (no tool loop) and streams
         *     its analysis of the surrounding semantic neighborhood as token
         *     frames; passages cited via [^k] resolve to the same
         *     CitationDrawer the chat surface uses. URL retained for backward
         *     compat with persisted trace history under
         *     ``${STORAGE_PATH}/fraud_ppr/...``.
         */
        post: operations["fraud_ppr_stream_insurance_fraud_ppr_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insurance/risk-predict/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Risk Predict Stream
         * @description Pre-issuance risk prediction (GraphAgent + PPR-anchored Sankey).
         *
         *     Wraps the graph agent runner: drives a fixed PPR → neighbors →
         *     read pipeline behind the ``prompt.risk_predict`` system prompt and
         *     augments the agent's ``final`` SSE event with a ``risk_subgraph``
         *     payload (3-layer ``customer_fields → risk_factors →
         *     triggered_clauses`` adjacency the frontend Sankey consumes).
         */
        post: operations["risk_predict_stream_insurance_risk_predict_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/messages/{message_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Message Trace
         * @description Return the assistant message's on-disk trace bundle.
         *
         *     Loads the message → its ``metadata_json.trace_path`` → resolves
         *     under STORAGE_PATH → reads ``query.json`` / ``trajectory.jsonl``
         *     / ``final.json`` / ``llm_calls.jsonl`` if present. Any missing
         *     artefact slot is omitted from the response (not an error).
         */
        get: operations["get_message_trace_chat_messages__message_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentStreamRequest
         * @description Body for ``POST /agent/stream`` (session-less).
         */
        AgentStreamRequest: {
            /** Query */
            query: string;
            /**
             * Kind
             * @default base
             * @enum {string}
             */
            kind: "base" | "proof" | "graph";
            /**
             * Web
             * @default false
             */
            web: boolean;
        };
        /** AuditEntryOut */
        AuditEntryOut: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number | null;
            /** Action */
            action: string;
            /** Target */
            target: string | null;
            /** Payload Json */
            payload_json: string | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /** Body_login_auth_login_post */
        Body_login_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** Body_upload_files_post */
        Body_upload_files_post: {
            /** File */
            file: string;
            /** Display Name */
            display_name?: string | null;
        };
        /**
         * ClaimCheckRequest
         * @description ``POST /insurance/claim-check/stream`` body.
         */
        ClaimCheckRequest: {
            /** File Ids */
            file_ids: string[];
            event: components["schemas"]["ClaimEvent"];
        };
        /** ClaimEvent */
        ClaimEvent: {
            /** Type */
            type: string;
            /**
             * Date
             * @description ISO date or human-readable.
             */
            date: string;
            /** Location */
            location?: string | null;
            /** Description */
            description: string;
            /** Amount */
            amount?: number | null;
        };
        /** ClusterBrief */
        ClusterBrief: {
            /** Canonical */
            canonical: string;
            /** Members */
            members: string[];
        };
        /**
         * CompareRequest
         * @description ``POST /insurance/compare/stream`` body.
         */
        CompareRequest: {
            /**
             * File Ids
             * @description Two-to-eight indexed product file_ids to compare.
             */
            file_ids: string[];
            /**
             * Properties
             * @description Comparison dimensions; each becomes a column. Free-form Chinese / English (e.g. '等待期', 'waiting period', '免责').
             */
            properties: string[];
        };
        /**
         * ConfigEntrySchema
         * @description One row in the admin UI's config table.
         */
        ConfigEntrySchema: {
            /** Key */
            key: string;
            /** Type */
            type: string;
            /** Default */
            default: unknown;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Group
             * @default
             */
            group: string;
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Min Length */
            min_length?: number | null;
            /** Max Length */
            max_length?: number | null;
        };
        /**
         * ConfigPatchRequest
         * @description Body for ``PATCH /admin/config`` — flat ``{key: value}`` map.
         */
        ConfigPatchRequest: {
            /**
             * Updates
             * @description Flat key→new-value map. Validated against the schema before any DB write — the patch is all-or-nothing.
             */
            updates: {
                [key: string]: unknown;
            };
        };
        /**
         * ConfigPatchResponse
         * @description Per-key diff returned after a successful PATCH.
         */
        ConfigPatchResponse: {
            /**
             * Diffs
             * @description Per-key ``{old, new}`` pairs. Mirrors what landed in the audit_log so the frontend can render an undo affordance.
             */
            diffs: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /**
             * Snapshot
             * @description Full effective config after the patch lands.
             */
            snapshot: {
                [key: string]: unknown;
            };
        };
        /**
         * ConfigSnapshotResponse
         * @description Shape returned by ``GET /admin/config``.
         */
        ConfigSnapshotResponse: {
            /**
             * Snapshot
             * @description Flat key→value map of the effective config.
             */
            snapshot: {
                [key: string]: unknown;
            };
            /**
             * Schema
             * @description Registered entries with their defaults / bounds. The admin UI uses these to render labels, helptext, and validation.
             */
            schema: components["schemas"]["ConfigEntrySchema"][];
        };
        /**
         * CustomerProfile
         * @description Shared customer-profile payload (exclusion audit + recommend).
         */
        CustomerProfile: {
            /** Age */
            age: number;
            /**
             * Gender
             * @enum {string}
             */
            gender: "M" | "F" | "X";
            /** Occupation */
            occupation: string;
            /** Occupation Risk */
            occupation_risk?: ("low" | "med" | "high") | null;
            /** Health History */
            health_history?: string[];
            /** Family History */
            family_history?: string[];
            /** Budget Annual */
            budget_annual?: number | null;
            /** Goal */
            goal?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * ExclusionAuditRequest
         * @description ``POST /insurance/exclusion-audit/stream`` body.
         */
        ExclusionAuditRequest: {
            /** File Id */
            file_id: string;
            customer: components["schemas"]["CustomerProfile"];
        };
        /** FileOut */
        FileOut: {
            /** File Id */
            file_id: string;
            /** Display Name */
            display_name: string;
            /** Original Filename */
            original_filename: string;
            /** Suffix */
            suffix: string;
            /** Byte Size */
            byte_size: number;
            /** Sha256 */
            sha256: string;
            /** Page Count */
            page_count: number | null;
            /** Status */
            status: string;
            /** Error Msg */
            error_msg: string | null;
            /** Uploaded By */
            uploaded_by: number | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Indexed At */
            indexed_at: string | null;
        };
        /**
         * FraudPPRRequest
         * @description ``POST /insurance/fraud-ppr/stream`` body.
         *
         *     Single PPR retrieval + single LLM analysis — no agent loop, no
         *     tool calls. The runner pre-fetches the subgraph server-side, so
         *     the request only carries the question (+ optional file_id scope).
         */
        FraudPPRRequest: {
            /** Query */
            query: string;
            /**
             * File Ids
             * @description Optional: prune passages to these file_ids only (max 50).
             */
            file_ids?: string[] | null;
        };
        /** GraphEdge */
        GraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Weight */
            weight: number;
            /** Type */
            type: string;
        };
        /**
         * GraphNode
         * @description One node in the G6 setData payload.
         */
        GraphNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Vertex Type */
            vertex_type: string;
            /**
             * Hop
             * @default 0
             */
            hop: number;
            /**
             * Score
             * @default 0
             */
            score: number;
        };
        /** GraphOverviewResponse */
        GraphOverviewResponse: {
            /**
             * Counts
             * @description Always carries ``nodes`` + ``edges`` plus per-vertex_type tallies (e.g. ``entity``, ``passage``, ``sentence``).
             */
            counts: {
                [key: string]: number;
            };
            /**
             * Top Central Entities
             * @description Top-10 entity vertices by degree (canvas first paint).
             */
            top_central_entities: components["schemas"]["NodeBrief"][];
        };
        /**
         * GraphSubgraphResponse
         * @description Generic subgraph shape — used by /expand AND /nodes/{id}/expand.
         */
        GraphSubgraphResponse: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestJobOut */
        IngestJobOut: {
            /** Id */
            id: number;
            /** File Id */
            file_id: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Error Msg */
            error_msg: string | null;
            /** Log Tail */
            log_tail: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MeOut */
        MeOut: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * MessagePost
         * @description User message body. mode/agent_kind come from the parent session.
         */
        MessagePost: {
            /** Content */
            content: string;
        };
        /**
         * NeighborFile
         * @description One entry of ``neighboring_files`` — file_id + readable name.
         */
        NeighborFile: {
            /** File Id */
            file_id: string;
            /** Display Name */
            display_name: string;
        };
        /** NodeBrief */
        NodeBrief: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Vertex Type */
            vertex_type: string;
            /** Degree */
            degree: number;
        };
        /**
         * NodeDetailResponse
         * @description Hover-card payload — no hash_id field (the URL already names it).
         *
         *     For passages, ``file_id`` + ``page_number`` are surfaced so the
         *     card can offer a "open in PDF" link without a second round trip.
         *     ``display_name`` accompanies any file_id so the UI can render the
         *     human-readable label instead of a sha-prefixed slug.
         */
        NodeDetailResponse: {
            /** Surface */
            surface: string;
            /** Vertex Type */
            vertex_type: string;
            /** Degree */
            degree: number;
            logical_cluster?: components["schemas"]["ClusterBrief"] | null;
            /** Mention Count */
            mention_count?: number | null;
            /** Neighboring Files */
            neighboring_files?: components["schemas"]["NeighborFile"][] | null;
            /** File Id */
            file_id?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Page Number */
            page_number?: number | null;
        };
        /** PPRActivedEntity */
        PPRActivedEntity: {
            /** Id */
            id: string;
            /** Surface */
            surface: string;
            /** Score */
            score: number;
            /** Iteration Tier */
            iteration_tier: number;
        };
        /** PPRPassage */
        PPRPassage: {
            /** Hash Id */
            hash_id: string | null;
            /** File Id */
            file_id: string;
            /** Page Id */
            page_id: string;
            /** Score */
            score: number;
        };
        /** PPRSeed */
        PPRSeed: {
            /** Id */
            id: string;
            /** Surface */
            surface: string;
            /** Similarity */
            similarity: number;
        };
        /** PPRSubgraphRequest */
        PPRSubgraphRequest: {
            /** Query */
            query: string;
            /**
             * File Ids
             * @description Optional: prune passages to these file_ids only (max 50).
             */
            file_ids?: string[] | null;
        };
        /**
         * PPRSubgraphResponse
         * @description ``mode`` distinguishes:
         *     * ``ppr``       — happy path, lists/edges populated
         *     * ``no_seeds``  — query had no entity match (UI: "no graph hit")
         *     * ``no_graph``  — graphml not built yet (UI: "graph not ready")
         */
        PPRSubgraphResponse: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "ppr" | "no_seeds" | "no_graph";
            /** Seeds */
            seeds: components["schemas"]["PPRSeed"][];
            /** Actived Entities */
            actived_entities: components["schemas"]["PPRActivedEntity"][];
            /** Passages */
            passages: components["schemas"]["PPRPassage"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /**
         * PasswordReset
         * @description Admin-side password reset. Lands as a new bcrypt hash.
         */
        PasswordReset: {
            /** New Password */
            new_password: string;
        };
        /**
         * PolicyCalcRequest
         * @description ``POST /insurance/policy-calc/stream`` body.
         *
         *     ``calc_targets`` is intentionally free-form: the agent has the
         *     actuarial vocabulary baked into ``prompt.policy_calc`` and can
         *     interpret natural-language asks like "Embedded Value 演示" /
         *     "premium-financing breakeven assuming 5% loan rate" without us
         *     having to enumerate every variant in a Literal. The frontend
         *     surfaces a chip set of common targets + an "其他" free text.
         */
        PolicyCalcRequest: {
            /** File Id */
            file_id: string;
            policy_params: components["schemas"]["PolicyParams"];
            /**
             * Calc Targets
             * @description Up to 6 free-text calc targets. Each ≤ 300 chars. Common: cash value by year, surrender value at year N, IRR to age 65, break-even year, embedded value (VIF + ANAV), NBV margin, premium-financing net IRR, IRR breakdown (guaranteed vs non-guaranteed).
             */
            calc_targets: string[];
        };
        /** PolicyParams */
        PolicyParams: {
            /** Age At Issue */
            age_at_issue: number;
            /**
             * Gender
             * @enum {string}
             */
            gender: "M" | "F" | "X";
            /**
             * Premium Mode
             * @default annual
             * @enum {string}
             */
            premium_mode: "annual" | "monthly" | "single";
            /** Premium Amount */
            premium_amount: number;
            /** Term Years */
            term_years: number;
            /** Sum Assured */
            sum_assured: number;
            /**
             * Currency
             * @default HKD
             */
            currency: string;
            /** Target Age */
            target_age?: number | null;
            /** Target Year */
            target_year?: number | null;
        };
        /**
         * RagStreamRequest
         * @description Body for ``POST /rag/stream`` (session-less).
         */
        RagStreamRequest: {
            /** Query */
            query: string;
        };
        /**
         * RecommendRequest
         * @description ``POST /insurance/recommend/stream`` body.
         *
         *     ``held_policies_file_ids`` lets the analyst hand the runner the
         *     customer's existing coverage so the model does gap-analysis
         *     instead of recommending duplicates. Optional — empty / None
         *     means "open corpus, recommend whatever fits".
         */
        RecommendRequest: {
            customer: components["schemas"]["CustomerProfile"];
            /**
             * Held Policies File Ids
             * @description Optional file_ids of policies the customer already holds. When supplied, the runner injects them into the prompt so the agent reads each one, summarises covered risks, then recommends complementary products only.
             */
            held_policies_file_ids?: string[] | null;
        };
        /**
         * RiskPredictRequest
         * @description ``POST /insurance/risk-predict/stream`` body.
         *
         *     Proactive (pre-issuance) risk prediction: given one candidate
         *     policy and a customer profile, the GraphAgent drives a fixed
         *     PPR → neighbors → read pipeline and emits a forward-looking risk
         *     forecast. ``scenario`` is an optional free-text hint (e.g.
         *     "客户考虑提前退保 / 计划三年内购房") that gets folded into the
         *     PPR query so the agent can bias its exploration toward that
         *     angle when supplied.
         */
        RiskPredictRequest: {
            /** File Id */
            file_id: string;
            customer: components["schemas"]["CustomerProfile"];
            /** Scenario */
            scenario?: string | null;
        };
        /**
         * SearchFilters
         * @description All filters compose as AND. ``None`` / empty = no constraint.
         */
        SearchFilters: {
            /** File Ids */
            file_ids?: string[] | null;
            /**
             * Page Range
             * @description Inclusive [start, end] page-number gate, 1-based.
             */
            page_range?: number[] | null;
            /**
             * Suffix
             * @description Filename-suffix whitelist (e.g. ['.pdf','.docx']).
             */
            suffix?: string[] | null;
        };
        /**
         * SearchHit
         * @description One result row. Shape varies subtly by granularity:
         *
         *     * ``granularity="page"``       — ``passage_id`` / ``table_row_id`` empty.
         *     * ``granularity="passage"``    — ``passage_id`` set.
         *     * ``granularity="table_row"``  — ``table_row_id`` set.
         */
        SearchHit: {
            /** File Id */
            file_id: string;
            /** Page Id */
            page_id: string;
            /** Page Number */
            page_number?: number | null;
            /** Passage Id */
            passage_id?: string | null;
            /** Table Row Id */
            table_row_id?: string | null;
            /** Score */
            score: number;
            /** Channel Scores */
            channel_scores?: {
                [key: string]: number;
            };
            /** Channels Hit */
            channels_hit?: string[];
            /**
             * Snippet
             * @default
             */
            snippet: string;
            /** Rerank Score */
            rerank_score?: number | null;
        };
        /**
         * SearchRequest
         * @description Body for ``POST /search``.
         */
        SearchRequest: {
            /** Query */
            query: string;
            /**
             * Granularity
             * @default page
             * @enum {string}
             */
            granularity: "page" | "passage" | "table_row";
            /**
             * Channels
             * @description At least one channel must be selected.
             */
            channels: ("semantic" | "bm25" | "graph_ppr" | "regex")[];
            filters?: components["schemas"]["SearchFilters"] | null;
            /** Rrf K */
            rrf_k?: number | null;
            /** Rrf Top M */
            rrf_top_m?: number | null;
            /**
             * Top N
             * @description Final hits returned. Default = admin rerank_top_n.
             */
            top_n?: number | null;
            /**
             * Rerank
             * @description Run the rerank model over the fused candidates. Off by default — adds latency + cost.
             * @default false
             */
            rerank: boolean;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /**
             * Granularity
             * @enum {string}
             */
            granularity: "page" | "passage" | "table_row";
            /** Channels Run */
            channels_run: ("semantic" | "bm25" | "graph_ppr" | "regex")[];
            /** Filters Applied */
            filters_applied?: {
                [key: string]: unknown;
            };
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
            /** N Total */
            n_total: number;
            /** N Returned */
            n_returned: number;
            /** Timings Ms */
            timings_ms?: {
                [key: string]: number;
            };
            /** Used Rrf */
            used_rrf: boolean;
            /** Used Rerank */
            used_rerank: boolean;
            /** Rrf K */
            rrf_k?: number | null;
            /** Rrf Top M */
            rrf_top_m?: number | null;
            /**
             * Post Filter Overfetched
             * @default false
             */
            post_filter_overfetched: boolean;
            /**
             * N Pre Filter
             * @default 0
             */
            n_pre_filter: number;
        };
        /** SeedHit */
        SeedHit: {
            /** Hash Id */
            hash_id: string;
            /** Surface */
            surface: string;
            /** Similarity */
            similarity: number;
            logical_cluster?: components["schemas"]["ClusterBrief"] | null;
        };
        /**
         * SessionCreate
         * @description Create-time payload. mode + agent_kind + web are immutable post-create.
         */
        SessionCreate: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "rag" | "agent";
            /** Agent Kind */
            agent_kind?: ("base" | "proof" | "graph") | null;
            /**
             * Web
             * @default false
             */
            web: boolean;
            /**
             * Title
             * @default New chat
             */
            title: string;
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "rag" | "agent";
            /** Agent Kind */
            agent_kind: ("base" | "proof" | "graph") | null;
            /**
             * Web
             * @default false
             */
            web: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SessionUpdate
         * @description Patchable session fields. mode / agent_kind intentionally not patchable.
         */
        SessionUpdate: {
            /** Title */
            title: string;
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Role */
            role: string;
            /** Username */
            username: string;
        };
        /**
         * UserCreate
         * @description Admin-side user creation payload.
         */
        UserCreate: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "analyst";
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "analyst";
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserUpdate
         * @description Patchable user fields. Username is immutable post-create.
         *
         *     All fields optional so callers can patch a single attribute
         *     without echoing the rest. The route rejects an empty body.
         */
        UserUpdate: {
            /** Role */
            role?: ("admin" | "analyst") | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WebRagStreamRequest
         * @description Body for ``POST /web-rag/stream`` (session-less smoke).
         */
        WebRagStreamRequest: {
            /** Query */
            query: string;
            /** Include Domains */
            include_domains?: string[] | null;
            /** Exclude Domains */
            exclude_domains?: string[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    list_all_files_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOut"][];
                };
            };
        };
    };
    upload_files_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_one_files__file_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_one_files__file_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_files__file_id__jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestJobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_jobs_files__file_id__jobs_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_original_files__file_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    page_preview_files__file_id__preview_get: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    page_count_endpoint_files__file_id__page_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reingest_files__file_id__reingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_audit_get: {
        parameters: {
            query?: {
                /** @description Exact action match, e.g. 'file.delete.complete' */
                action?: string | null;
                /** @description Exact target match (typically a file_id) */
                target?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_entry_audit__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_chat_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_chat_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_detail_chat_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_chat_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_session_chat_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_session_message_chat_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessagePost"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rag_stream_rag_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RagStreamRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_stream_agent_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentStreamRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    web_rag_stream_web_rag_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebRagStreamRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_admin_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSnapshotResponse"];
                };
            };
        };
    };
    patch_config_admin_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigPatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schema_admin_config_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigEntrySchema"][];
                };
            };
        };
    };
    reset_config_admin_config__key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_indexes_admin_refresh_indexes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users_admin_users_get: {
        parameters: {
            query?: {
                /** @description Include soft-deleted users. */
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_admin_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    soft_delete_user_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_user_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_admin_users__user_id__reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordReset"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_graph_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphOverviewResponse"];
                };
            };
        };
    };
    search_seed_graph_seed_get: {
        parameters: {
            query: {
                /** @description Entity name to fuzzy-match */
                q: string;
                top_k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sample_graph_graph_sample_get: {
        parameters: {
            query?: {
                n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphSubgraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    expand_node_graph_expand_get: {
        parameters: {
            query: {
                /** @description hash_id of the seed vertex */
                node_id: string;
                hops?: number;
                top_k?: number;
                /** @description Filter applied to non-seed nodes only. */
                vertex_type?: string;
                /** @description Optional: prune passage vertices to these file_ids (max 50). */
                file_ids?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphSubgraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_detail_graph_nodes__hash_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hash_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ppr_subgraph_graph_ppr_subgraph_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PPRSubgraphRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PPRSubgraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_stream_insurance_compare_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exclusion_audit_stream_insurance_exclusion_audit_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExclusionAuditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_stream_insurance_recommend_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_check_stream_insurance_claim_check_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    policy_calc_stream_insurance_policy_calc_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyCalcRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fraud_ppr_stream_insurance_fraud_ppr_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FraudPPRRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    risk_predict_stream_insurance_risk_predict_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskPredictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_message_trace_chat_messages__message_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
