"""v0.1 — initial baseline.

Captures the 7 ORM tables — users / files / ingest_jobs /
chat_sessions / chat_messages / app_config / audit_log — plus
indexes and CHECK constraints. Future migrations depend on this
revision.

Revision ID: v0_1
Revises:
Create Date: 2026-05-08 14:39:25.118722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'v0_1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('admin','analyst')", name='ck_users_role'),
    sa.CheckConstraint('is_active IN (0,1)', name='ck_users_is_active'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('app_config',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_at', ['at'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('agent_kind', sa.String(length=16), nullable=True),
    sa.Column('web', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(mode = 'agent' AND agent_kind IS NOT NULL) OR (mode = 'rag' AND agent_kind IS NULL)", name='ck_sessions_mode_kind'),
    sa.CheckConstraint("agent_kind IS NULL OR agent_kind IN ('base','proof','graph')", name='ck_sessions_agent_kind'),
    sa.CheckConstraint("mode IN ('rag','agent')", name='ck_sessions_mode'),
    sa.CheckConstraint("web = 0 OR mode = 'rag' OR (mode = 'agent' AND agent_kind = 'base')", name='ck_sessions_web_compatible'),
    sa.CheckConstraint('web IN (0, 1)', name='ck_sessions_web_bool'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_user_updated', ['user_id', 'updated_at'], unique=False)

    op.create_table('files',
    sa.Column('file_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('suffix', sa.String(length=16), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','parsing','indexing','ready','failed','deleting')", name='ck_files_status'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('file_id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_sha256'), ['sha256'], unique=False)
        batch_op.create_index('ix_files_status', ['status'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant','tool','system')", name='ck_msg_role'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_session_id', ['session_id', 'id'], unique=False)

    op.create_table('ingest_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('log_tail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('parse_index','reingest','delete')", name='ck_jobs_kind'),
    sa.CheckConstraint("status IN ('pending','running','done','failed')", name='ck_jobs_status'),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_file_id', ['file_id'], unique=False)
        batch_op.create_index('ix_jobs_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingest_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status')
        batch_op.drop_index('ix_jobs_file_id')

    op.drop_table('ingest_jobs')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_session_id')

    op.drop_table('chat_messages')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index('ix_files_status')
        batch_op.drop_index(batch_op.f('ix_files_sha256'))

    op.drop_table('files')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_updated')

    op.drop_table('chat_sessions')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_at')

    op.drop_table('audit_log')
    op.drop_table('app_config')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
